envs:
  global:
    variables:
      registry: 'ultronregistry.azurecr.io'
      username: 'vn000de@homeoffice.wal-mart.com'
      password: 'Walmart12'
      app_service_sc: 'hellowWorld.scm.azurewebsites.net'
#      acrName: 'ultronregistry.azurecr.io' #here goes your container registry name
#      acrCred: 'aMXJ+kXPXmQ2QjORz1fSsKEcSthW7TkR' #here goes your looper credential for the container registry

flows:
  default:
    - exposeVars(maven)
    - var(text = 'Starting new build => *_${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}_*')
    - call: maven-build
    - exposeVars(maven)
    - var(text = 'Released *_${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}_* to WaRM')
    - call: app-docker-deploy(dev)
    - call: app-azure-deploy(dev)

  pr:
    - exposeVars(maven)
    - var(text = 'Building new PR => *_${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}_* || $GITHUB_PR_URL')
    - call: maven-test

  app-docker-deploy:
    - node(docker-daemon):
      - mvn clean install
      - exposeVars(maven)
      - dockerImage:
          tags:
            - '${registry}/process-api:${MAVEN_VERSION}'
            - '${registry}/process-api'
          push: true
          baseDir: './'
          buildArgs:
          creds:
            ultronregistry.azurecr.io: 'aMXJ+kXPXmQ2QjORz1fSsKEcSthW7TkR'

  app-azure-deploy:
    - switch(${env}):
        case('dev'):
          - curl -XPOST -H Content-Length:0 -v https://${username}:${password}@$hellowWorld.scm.azurewebsites.net/docker/hook

